import "./globals.css";
import Navbar from "../components/navbar";
import Sidebar from "../components/sidebar";
import type { Metadata } from "next";
import { VisibilityProvider } from "@/components/Content/context";


export const metadata: Metadata = {
  title: "FutureHQNT",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <VisibilityProvider>
          <div className="flex">
            <div className="">
              <Sidebar />
            </div>
            <div className="w-full ">
              <div>
                <Navbar />
              </div>
              <div className=" bg-gray-100 max-lg:relative ">
                {children}
              </div>
            </div>
          </div>
        </VisibilityProvider>

      </body>
    </html>
  );
}
